name: Terraform Destroy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/144477738388/locations/global/workloadIdentityPools/github-pool/providers/github-provider"

          service_account: "terraform-gke-sa@mycompany-dev-496016.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve